.PHONY: run logs

# Ensure the virtual environment is activated and run the script
run:
	@echo "Starting Game..."
	@source ./bin/activate && python main.py

# Tail the log file
logs:
	@tail -f game.log
